import Head from 'next/head'

export default function GetInitialProps() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       test

      </main>
    </>
  )
}

GetInitialProps.getInitialProps = async () => {
  throw new Error('Service Unavailable')
}